# Generated by Django 4.2.1 on 2023-06-05 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('mileage', models.IntegerField(default=0)),
                ('body_type', models.CharField(choices=[('L', 'Limunzina'), ('H', 'Hečbek'), ('K', 'Karavan')], default='L', max_length=1)),
                ('fuel_type', models.CharField(choices=[('B', 'Benzin'), ('D', 'Dizel'), ('G', 'Gas (TNG)'), ('E', 'Električni pogon'), ('H', 'Hibridni pogon')], default='B', max_length=1)),
                ('gearbox', models.CharField(choices=[('M', 'Manuelni'), ('A', 'Automatski')], default='M', max_length=1)),
                ('power', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='offer.offer')),
            ],
        ),
    ]
