# Generated by Django 4.2.1 on 2023-06-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
