# Generated by Django 4.2.1 on 2023-06-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_reported'),
        ('company', '0003_review_firm_alter_review_user_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='offer.offer'),
        ),
    ]
