# Generated by Django 4.2.1 on 2023-05-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
