# Generated by Django 4.2.1 on 2023-05-28 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_car_price_alter_car_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='search.car')),
            ],
        ),
    ]
